// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace MusicQuiz.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContext : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RoleId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionMusicFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceMusicFilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("WrongAnswerOne")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WrongAnswerThree")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WrongAnswerTwo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectAnswer = "1.25kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1.25kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 2,
                            CorrectAnswer = "1.25kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1.25kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 3,
                            CorrectAnswer = "1.25kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1.25kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 4,
                            CorrectAnswer = "1.6kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1.6kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 5,
                            CorrectAnswer = "1.6kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1.6kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 6,
                            CorrectAnswer = "1.6kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1.6kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 7,
                            CorrectAnswer = "100Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/100Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 8,
                            CorrectAnswer = "100Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/100Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 9,
                            CorrectAnswer = "100Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/100Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 10,
                            CorrectAnswer = "10kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/10kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 11,
                            CorrectAnswer = "10kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/10kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 12,
                            CorrectAnswer = "10kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/10kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 13,
                            CorrectAnswer = "12.5kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/12.5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 14,
                            CorrectAnswer = "12.5kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/12.5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 15,
                            CorrectAnswer = "12.5kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/12.5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 16,
                            CorrectAnswer = "125Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/125Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 17,
                            CorrectAnswer = "125Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/125Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 18,
                            CorrectAnswer = "125Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/125Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 19,
                            CorrectAnswer = "160Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/160Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 20,
                            CorrectAnswer = "160Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/160Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 21,
                            CorrectAnswer = "160Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/160Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 22,
                            CorrectAnswer = "16kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/16kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 23,
                            CorrectAnswer = "16kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/16kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 24,
                            CorrectAnswer = "16kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/16kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 25,
                            CorrectAnswer = "1kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 26,
                            CorrectAnswer = "1kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 27,
                            CorrectAnswer = "1kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/1kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 28,
                            CorrectAnswer = "2.5kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/2.5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 29,
                            CorrectAnswer = "2.5kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/2.5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 30,
                            CorrectAnswer = "2.5kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/2.5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 31,
                            CorrectAnswer = "200Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/200Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 32,
                            CorrectAnswer = "200Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/200Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 33,
                            CorrectAnswer = "200Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/200Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 34,
                            CorrectAnswer = "250Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/250Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 35,
                            CorrectAnswer = "250Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/250Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 36,
                            CorrectAnswer = "250Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/250Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 37,
                            CorrectAnswer = "2kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/2kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 38,
                            CorrectAnswer = "2kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/2kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 39,
                            CorrectAnswer = "2kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/2kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 40,
                            CorrectAnswer = "3.15kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/3.15kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 41,
                            CorrectAnswer = "3.15kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/3.15kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 42,
                            CorrectAnswer = "3.15kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/3.15kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 43,
                            CorrectAnswer = "315Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/315Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 44,
                            CorrectAnswer = "315Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/315Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 45,
                            CorrectAnswer = "315Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/315Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 46,
                            CorrectAnswer = "400Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/400Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 47,
                            CorrectAnswer = "400Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/400Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 48,
                            CorrectAnswer = "400Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/400Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 49,
                            CorrectAnswer = "4kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/4kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 50,
                            CorrectAnswer = "4kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/4kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 51,
                            CorrectAnswer = "4kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/4kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 52,
                            CorrectAnswer = "500Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/500Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 53,
                            CorrectAnswer = "500Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/500Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 54,
                            CorrectAnswer = "500Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/500Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 55,
                            CorrectAnswer = "5kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 56,
                            CorrectAnswer = "5kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 57,
                            CorrectAnswer = "5kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/5kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 58,
                            CorrectAnswer = "6.3kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/6.3kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 59,
                            CorrectAnswer = "6.3kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/6.3kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 60,
                            CorrectAnswer = "6.3kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/6.3kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 61,
                            CorrectAnswer = "630Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/630Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 62,
                            CorrectAnswer = "630Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/630Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 63,
                            CorrectAnswer = "630Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/630Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 64,
                            CorrectAnswer = "63Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/63Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 65,
                            CorrectAnswer = "63Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/63Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 66,
                            CorrectAnswer = "63Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/63Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 67,
                            CorrectAnswer = "800Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/800Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 68,
                            CorrectAnswer = "800Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/800Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 69,
                            CorrectAnswer = "800Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/800Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 70,
                            CorrectAnswer = "80Hz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/80Hz.wav",
                            ReferenceMusicFilePath = "/Music/SineWave/400Hz.wav",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 71,
                            CorrectAnswer = "80Hz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/80Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 72,
                            CorrectAnswer = "80Hz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/80Hz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 73,
                            CorrectAnswer = "8kHz",
                            DifficultyId = 1,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/8kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 74,
                            CorrectAnswer = "8kHz",
                            DifficultyId = 2,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/8kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        },
                        new
                        {
                            Id = 75,
                            CorrectAnswer = "8kHz",
                            DifficultyId = 3,
                            Question = "Identify the correct frequency.",
                            QuestionMusicFilePath = "/Music/SineWave/8kHz.wav",
                            ReferenceMusicFilePath = "",
                            TopicId = 1,
                            WrongAnswerOne = "800Hz",
                            WrongAnswerThree = "2kHz",
                            WrongAnswerTwo = "1.5kHz"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
